### ISSUE TITLE
HMcode-2020 feedback issue

### ISSUE THREAD

**Issue by alexander-mead** [tilmantroester/pyhmcode#4]
There was a small problem with the predictions from the HMcode-2020 feedback model at very low k. These are described here: https://github.com/cmbant/CAMB/issues/135. HMcode-2020 with feedback would erroneously predict ~10% level effects on the power at k ~ 1e-4 h/Mpc.

I was able to fix these by changing the form of the one-halo term at large scales, which goes into the HMcode prediction for feedback, which is modelled as a response. The change can be seen here:

Before:
![before](https://user-images.githubusercontent.com/9140961/211616945-6f13ac86-cf75-4acb-8868-2e2006f461f6.png)

After:
![after](https://user-images.githubusercontent.com/9140961/211616988-9894d578-81b4-4d05-aa48-07159b21ea3b.png)

You will need to pull the latest version of my Fortran library to have access to this fix, and also change the halo model corresponding to HMcode-2020 feedback from `HMcode2020_feedback` (number 103 in my numbering convention) to `HMcode2020_feedback_lowkfix` (number 141).

**Comment by sjoudaki** [comment]
@alexander-mead This is a really nice fix! @tilmantroester It seems having this included in pyhmcode would also be useful for the nonlinear task force in Euclid.

**Comment by tilmantroester** [comment]
I'm happy to accept pull requests ;)

**Comment by alexander-mead** [comment]
Ha! I can probably do this next week.

**Comment by tilmantroester** [comment]
This should now be covered with #9
